<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type"content="text/html;charset=iso-8859-1"/>
	<tittle>listado5-4.html.ejemplo de estructuras if...else</tittle>
</head>
<body>
	<script type="text/javascript">
		var nombre;
		nombre= prompt("hola,¿quien eres,carlos o lydia?",**);
		if ((nombre=="carlos")||(nombre=="lydia")){
			alert("buenos dias" +nombre+",hace rato que te esperaba,");
		}
		else
		{
			alert("no te conozco" +nombre+",pero de todos modos, buenos dias ");
		}
	</script>
</body>
</html>